/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador.calctop;


/**
 *
 * @author eduar
 */
public class TelaPrincipal extends javax.swing.JFrame {
    HistoricoTela h = new HistoricoTela();
    int contHist=0;

 
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ajuda = new javax.swing.JMenu();
        historico = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuConvertPressao = new javax.swing.JMenuItem();
        menuConvertCapacidade = new javax.swing.JMenuItem();
        menuConvertComprimento = new javax.swing.JMenuItem();
        menuConvertTemperatura = new javax.swing.JMenuItem();
        menuConvertBaseNumerica = new javax.swing.JMenuItem();
        menuConvertGeometria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalcTop");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/Logo1.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);

        ajuda.setText("Arquivo");

        historico.setText("Historico");
        historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoActionPerformed(evt);
            }
        });
        ajuda.add(historico);

        sobre.setText("Sobre");
        sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreMouseClicked(evt);
            }
        });
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        ajuda.add(sobre);
        ajuda.add(jSeparator1);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        ajuda.add(sair);

        jMenuBar1.add(ajuda);

        jMenu2.setText("Conversões");

        menuConvertPressao.setText("Pressão");
        menuConvertPressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvertPressaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuConvertPressao);

        menuConvertCapacidade.setText("Capacidade");
        menuConvertCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvertCapacidadeActionPerformed(evt);
            }
        });
        jMenu2.add(menuConvertCapacidade);

        menuConvertComprimento.setText("Comprimento");
        menuConvertComprimento.setToolTipText("");
        menuConvertComprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvertComprimentoActionPerformed(evt);
            }
        });
        jMenu2.add(menuConvertComprimento);

        menuConvertTemperatura.setText("Temperatura");
        menuConvertTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvertTemperaturaActionPerformed(evt);
            }
        });
        jMenu2.add(menuConvertTemperatura);

        menuConvertBaseNumerica.setText("Base Numérica");
        menuConvertBaseNumerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvertBaseNumericaActionPerformed(evt);
            }
        });
        jMenu2.add(menuConvertBaseNumerica);

        menuConvertGeometria.setText("Geometria");
        menuConvertGeometria.setToolTipText("");
        menuConvertGeometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvertGeometriaActionPerformed(evt);
            }
        });
        jMenu2.add(menuConvertGeometria);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoActionPerformed
        
        h.setVisible(true);
            
    }//GEN-LAST:event_historicoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void sobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMouseClicked
        
    }//GEN-LAST:event_sobreMouseClicked

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        Sobre s = new Sobre();
        //this.dispose();
        s.setVisible(true);
        
    }//GEN-LAST:event_sobreActionPerformed

    private void menuConvertPressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvertPressaoActionPerformed
        Conversao c = new Conversao();
        String []n = {"PSI","BAR"};
        this.dispose();
        c.setVisible(true);
        c.renomearLbl("Pressao");
        c.renomearUnid(2, n);
    }//GEN-LAST:event_menuConvertPressaoActionPerformed

    private void menuConvertCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvertCapacidadeActionPerformed
        Conversao c = new Conversao();
        String n[] = {"Cm³", "Dm³","Galão","Litro","M³","Quilolitro"};
        this.dispose();
        c.setVisible(true);
        c.renomearLbl("Capacidade");
        c.renomearUnid(6, n);
    }//GEN-LAST:event_menuConvertCapacidadeActionPerformed

    private void menuConvertBaseNumericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvertBaseNumericaActionPerformed
        Conversao c = new Conversao();
        String n[] = {"Binária","Decimal","Hexadecimal","Octal"};
        this.dispose();
        c.setVisible(true);
        c.renomearLbl("Base Numérica");
        c.renomearUnid(4, n);
    }//GEN-LAST:event_menuConvertBaseNumericaActionPerformed

    private void menuConvertTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvertTemperaturaActionPerformed
        Conversao c = new Conversao();
        String n[] = {"Celsius","Fahrenheit","Kelvin"};
        this.dispose();
        c.setVisible(true);
        c.renomearLbl("Temperatura");
        c.renomearUnid(3, n);
    }//GEN-LAST:event_menuConvertTemperaturaActionPerformed

    private void menuConvertComprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvertComprimentoActionPerformed
        Conversao c = new Conversao();
        c.ligaBtn();
        String []n = {"Metro","Milhas","Polegada","Quilômetro"};
        this.dispose();
        c.setVisible(true);
        c.renomearLbl("Comprimento");
        c.renomearUnid(4, n);
    }//GEN-LAST:event_menuConvertComprimentoActionPerformed

    private void menuConvertGeometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvertGeometriaActionPerformed
        Conversao c = new Conversao();
        String []n = {"Graus","Radianos"};
        this.dispose();
        c.setVisible(true);
        c.renomearLbl("Geometria");
        c.renomearUnid(2, n);    
    }//GEN-LAST:event_menuConvertGeometriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenuItem historico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuConvertBaseNumerica;
    private javax.swing.JMenuItem menuConvertCapacidade;
    private javax.swing.JMenuItem menuConvertComprimento;
    private javax.swing.JMenuItem menuConvertGeometria;
    private javax.swing.JMenuItem menuConvertPressao;
    private javax.swing.JMenuItem menuConvertTemperatura;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem sobre;
    // End of variables declaration//GEN-END:variables
}
